### ISSUE TITLE
bn.js 적용

### ISSUE THREAD

**Issue by myungjunChae** [likelion-liquidity/liquidity-contract#28]
- decode, encode 코드 작성
```
//수도코드
const encode = (value) => {
  return new BigNumber(value).times(new BigNumber(10 ** 18));
}
```

- Ltv 등 BN 적용되어있지않은 코드에 BN 적용

**Comment by jjgob** [comment]
라이브러리 별로 테스트 한 결과입니다. 참고 바랍니다~
------------
console.log("## bn.js         => " + new BN(99.123456789123456789).toString());
console.log("## bn.js         => " + new BN(0.123456789123456789).toString());
console.log("## bn.js         => " + new BN("99.123456789123456789").toString());
console.log("## bn.js         => " + new BN("0.123456789123456789").toString());
console.log("## bignumber.js  => " + new BigNumber(99.123456789123456789).toString());
console.log("## bignumber.js  => " + new BigNumber(0.123456789123456789).toString());
console.log("## bignumber.js  => " + new BigNumber("99.123456789123456789").toString());
console.log("## bignumber.js  => " + new BigNumber("0.123456789123456789").toString());
console.log("## bigdecimal.js => " + new Big(99.123456789123456789).toString());
console.log("## bigdecimal.js => " + new Big(0.123456789123456789).toString());
console.log("## bigdecimal.js => " + new Big("99.123456789123456789").toString());
console.log("## bigdecimal.js => " + new Big("0.123456789123456789").toString());
console.log("## bigdecimal    => " + new bigdecimal.BigDecimal(99.123456789123456789).toString());
console.log("## bigdecimal    => " + new bigdecimal.BigDecimal(0.123456789123456789).toString());
console.log("## bigdecimal    => " + new bigdecimal.BigDecimal("99.123456789123456789").toString());
console.log("## bigdecimal    => " + new bigdecimal.BigDecimal("0.123456789123456789").toString());
------ console.log -----------
## bn.js         => 99
## bn.js         => 0
## bn.js         => 988123456789123456789
## bn.js         => -18719undefined-7250238undefined-5172715
## bignumber.js  => 99.12345678912345
## bignumber.js  => 0.12345678912345678
## bignumber.js  => 99.123456789123456789
## bignumber.js  => 0.123456789123456789
## bigdecimal.js => 99.12345678912345
## bigdecimal.js => 0.12345678912345678
## bigdecimal.js => 99.123456789123456789
## bigdecimal.js => 0.123456789123456789
## bigdecimal    => 99.123456789123451927
## bigdecimal    => 0.12345678912345678380
## bigdecimal    => 99.123456789123456789
## bigdecimal    => 0.123456789123456789

**Comment by jjgob** [comment]
bn.js new할때 10진수로 명시해줘도 똑같이 나옵니다. 
-------------------------------------------------
console.log("=> bn.js         : " + new BN(99.123456789123456789, 10).toString());
console.log("=> bn.js         : " + new BN(0.123456789123456789, 10).toString());
console.log("=> bn.js         : " + new BN("99.123456789123456789", 10).toString());
console.log("=> bn.js         : " + new BN("0.123456789123456789", 10).toString());
------ console.log -----------
=> bn.js         : 99
=> bn.js         : 0
=> bn.js         : 988123456789123456789
=> bn.js         : -18719undefined-7250238undefined-5172715

**Comment by jjgob** [comment]
일단 공통함수로 만들어 봤습니다. 
-------------------------
/**
 * convertToBigNumber : BigNumber로 변환
 * ex) await convertToBigNumber("99.123456789123456789", 18) => 99123456789123456789
 * ex) await convertToBigNumber("0.123456789123456789", 18) => 123456789123456789
 * ex) await convertToBigNumber("99123456789123456789", -18) => 99.123456789123456789
 * ex) await convertToBigNumber("123456789123456789", -18) => 0.123456789123456789
 */
const convertToBigNumber = async (input, decimal) => {
    if (!input) {
        return new BigNumber(0);
    }

    let bn = new BigNumber(input);
    if (!decimal) {
        return bn;
    }
    if (Number(decimal) > 0) {
        return bn.times(new BigNumber(10 ** Number(decimal)));
    } else {
        return bn.div(new BigNumber(10 ** -Number(decimal)));
    }
};

**Comment by myungjunChae** [comment]
`convertToBigNumber`가 비동기로 작성되어야할 이유가 있을까요??

추가적으로 decimal을 파라미터로 받아서 확장성을 취하는 코드는 좋다고 생각하나, `* 10^18`, `/ 10^18`이 두가지 밖에 사용하지 않을 것 같아서, 개인적으로는 메소드를 두개로 나누는 게 추후에 사용성 측면에서 우수하지 않나 생각됩니다!

**Comment by jjgob** [comment]
let x = 10;
x = convertToBigNumber(x);
call function (x)
이렇게 사용하는 경우가 있으면  async가 아니면 convert되기 전 값인 10이 펑션의 파라미터로 들어가기도 한다고 생각해서
async를 쓰긴 했는데
줄곧 이렇게 써서... 안써도 되는건가요??

**Comment by jjgob** [comment]
펑션은 그럼 encode, decode로 가겠습니다.

**Comment by myungjunChae** [comment]
만약 convert와 관련된 로직이 비동기로 작성되어있으면, 유나님께서 작성하신 방향대로 async로 작성하시는게 맞아보입니다.

저희가 코드에서 비동기를 작성하는 이유는  I/O (네트워크, DB) 등의 작업이 얼마나 걸릴지 모르기때문에, 메인스레드에서 해당 작업을 독점하고 있으면, 다른 로직들을 처리할 수 없기때문인데요.

단순 new BN 로직은 I/O작업이 아니고, 해당 로직 또한 동기식으로 제공되고있어서, convert 함수가 비동기로 작성될 필요는 없다고 생각합니다!

**Comment by myungjunChae** [comment]
encode, decode 의견 반영해주셔서 감사합니다 (_ _
